name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - feature/*
      - fix/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out TS Project Git repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install Node.js dependencies
        run: npm i

      - name: Run lint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test
